---
title: "El Pinacate"
author: "Miguel Equihua"
lang: es

format: 
  html: default
  docx: 
    reference-doc: custom-reference-doc.docx
---

En 1980 el gobernador del estado de Sonora, Samuel Ocaña, invitó al Inecol a realizar estudios que conducirían a establecer una nueva reserva de la biosfera en México. El área elegida era la hermosa región del Pinacate, en el territorio del desierto sonorense. Seguramente lo inspiraban las flamantes reservas de la biosfera de Mapimí y la Michilía en Durango. Sin duda también era un estímulo sumarse a la innovación que significaba el naciente y ambicioso planteamiento del **proyecto 8**, del entonces todavía nuevo programa **MAB** creado por la **UNESCO** en 1970. El **Proyecto 8** *impulsa la creación de un sistema mundial de reservas de la biosfera* mediante el cual se buscaría preservar porciones significativas de los ecosistemas del mundo.

El Pinacate sin duda es una joya para este notable planteamiento. El Inecol, dirigido entonces por su fundador Gonzalo Halffter, convoca al nuevo miembro del Inecol, Exequiel Ezcurra, llegado de Argentina aénas el año anterior, a encabezar y formar un equipo multidisciplinario de trabajo para realizar los estudios solicitados. En el grupo estábamos el propio Exequiel, Jorge López-Portillo, un colaborador de Inegi, Enrique Lagunes y yo, enfocados a hacer la cartografía, zonificación ecológica e inventario botánico. Además, Alberto González y Jorge Nocedal se abocaron al estudio de la fauna.

Nuestro primer encuentro con esta majestuosa porción del planeta nos impresionó profundamente. Desde el aire se aprecia el gran escudo basáltico negruzco que han formado los más de 400 volcanes que ahí existen, enmarcado por las arenas vivas del Grand Desierto de Altar. Caminar este paisaje es una experiencia sobrecogedora. Lo exploramos poco a poco. A veces con temperaturas cercanas a los 50°C. Anduvimos por la costa de la bahía de Adair, con sus amplias llanuras lodosas, marismas, dunas, salinas y minúsculos oasis. Pasamos por las imponentes dunas vivas del Gran Desierto de Altar y, desde luego, el majestuosos y complejo escudo basáltico salpicado por los nueve cráteres llamados *maar* por los especialistas, que lo hace la mayor conentración de este tipo de formaciones geológicas en el mundo. Estos *maar* dan al paisaje un aspecto facinante. El más grande de ellos aquí es el Elegante, que tiene casi dos kilómetros de diámetro y cerca de 250 m de profundidad. Está casi a nivel del suelo y sólo cuando se acerca el visitante lo descubre de súbito en todo su esplendor. Subimos hasta la cima del Pinacate, formado por dos volcanes, hasta una elevación de poco más de 1,200 msnm. 

En cada ambiente hicimos muestreos de vegetación en cuadrados y transectos, para obtener datos numéricos sobre la composición y abundancia de las plantas de cada lugar. De vez en cuando nos topamos con habitantes del lugar, humanos y no humanos, como los berrendos, que un buen día nos sorprendieron en una llanura, lo que nos obligo a detenernos en seco para saludarlos a la distancia y maravillarnos con su hermosura. Ellos nos correspondieron saliendo a toda carrera para mantener su distancia. Tuvimos la oportunidad de ver llover en el desierto y también de ser testigos del milagro de verlo florecer en cuestión de días, con el regalo que hacen a la vista las hermosas flores de *Abronia villosa* S. Watson, *Oenothera deltoides* Torr. & Frém. y del ocotillo. También nos deleitamos al ver a los Sahuaros (*Carnegiea gigantea* (Engelm.) Britton & Rose) copeteados con sus flores blancas, . Pasado algún tiempo esas flores se tornaron en frutos y nos extasió ver a esos frutos abrirse como nuevas flores, ahora rojas y deliciosas. A la distancia, las choya güera que en el inglés de las guías que usabamos conocimos como *teddy bear choya* (*Cylindropuntia bigelovii* (Engelm.) F.M.Knuth), se aprecia acariciable. pero el contacto cercano revela la ferocidad de sus espinas, como muchas veces tuvimos oportunidad de comprobar.

Los datos que recogimos en estas travesías lo organizamos con ayuda de una reluciente microcomputadora **Apple II plus**, con procesador de 8 bits y 64kbytes de memoria RAM. Una de esas máquinas que inauguraron la revolución de las computadoras personales ahora ubicuas. En ella sistematizamos los datos de campo con ayuda de una base de datos y la programamos en *fortran* y *Pascal* para realizar lo que pienso fueron ensayos pioneros de clasificación numérica de la vegetación. Con este enfoque, dirigido por Exequiel que había incursionado en estos temas en sus estudios de maestría en Inglaterra, propusimos una caracterización ecológica del área de estudio que consideraba 9 unidades de vegetación. Contrastando notablemente los ambientes rocosos de los demás. El ocotillo (*Fouqueria splendens* Engelm.) emergió en esta perspectiva como una marca para distinguir esta gran dicotomía. Los ambientes rocosos notablemente más ricos en composición.

Tras tres años de estudios se elaboró una propuesta de decreto para la **Reserva de la Biosfera El Pinacate**, pero desafortunadamente no se le dio seguimiento por muchos años. Finalmente, en 1993, fue publicado el decreto que declara la creación del área natural protegida, con el carácter de Reserva de la Biosfera, a la región conocida como El Pinacate y Gran Desierto de Altar, ubicada en los municipios de Plutarco Elías Calles, Puerto Peñasco y San Luis Río Colorado. Algunos años más adelate, en 2013, también sería reconocido como **Patrimonio Mundial** por la UNESCO, considerando su excepcional belleza paisajística, confluencia única de geoformas y extraordinaria biodiversidad.

Hoy, el Pinacate es un área natural protegida emblemática. Cuenta con un centro de Visitantes llamado *Schuk Toak*,  que recupera el sentir del pueblo pápago (los *Tohono O’odham* como se nombran ellos mismos en su propia lengua). Así lo llaman, pues para ellos es *la Montaña Sagrada* . Sin duda es un enorme privilegio haber sido parte de esta historia, de las vivencias compartidas y de los afanes que finalmente culminaron en honrar al Pinacate, al *Shuk Toak*, como patrimonio de la humanidad.
